name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  iirjdart: ^0.0.1
  circular_check_box:
    git:
      url: git://github.com/Supercaly/circular_check_box
      ref: development
  powerdart:
    path: ../../power_dart/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  about_dependencies:
    path: ../

flutter:
  uses-material-design: true